### ISSUE TITLE
Respin the wheel

### ISSUE THREAD

**Issue by aks7665** [Sayegh7/ngx-wheel#12]
I am facing an issue. I want to spin the wheel again. Currently what happens if we have spined the wheel once than after if i click on the spin button. It doesn't re spin the wheel. How we can re spin the wheel?

And one more issue is if we update the items array than it is not reflecting changes to wheel item.

**Comment by Sayegh7** [comment]
Both of these issues can be solved by updating to `4.0.5` and calling the `reset` function as described [here](https://github.com/Sayegh7/ngx-wheel#accessing-wheel-functions). Make sure to call the reset function after updating the items array and/or to allow re-spinning.

**Comment by aks7665** [comment]
Thanks
