### ISSUE TITLE
Question: Demo App

### ISSUE THREAD

**Issue by jek-bao-choo** [Sayegh7/ngx-wheel#6]
Hi @Sayegh7 

You created this demo app on https://sayegh7.github.io/ngx-wheel/

May I know where to find this demo app? 

I want to try having it spin on button press. Not when clicked on the wheel.

Thanks.

**Comment by Sayegh7** [comment]
Hi @choopage, the demo is outdated I'm afraid. The current behavior of the wheel supports clicking or dragging it with the mouse only. I will add it in the future, but if you are in a hurry, all PRs are welcome :)

**Comment by Sayegh7** [comment]
New demo link https://ngx-wheel.web.app/
